'use strict';

const PokeListActionTypes = {
  FETCH_POKEMON_LIST: 'FETCH_POKEMON_LIST',
  APPEND_POKEMON_LIST: 'APPEND_POKEMON_LIST',
  OPEN_POKEMON_DETAIL: 'OPEN_POKEMON_DETAIL',

  FILTER_POKEMON_BY_TYPES: 'FILTER_POKEMON_BY_TYPES',
  RESET_FILTER: 'RESET_FILTER'
}

export default PokeListActionTypes;